// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE50H8MXYZ3hPbnkgbpFP8zsVUjhtP23o',
    appId: '1:1015927427902:web:23ba5a64396914898b926f',
    messagingSenderId: '1015927427902',
    projectId: 'ayra-386206',
    authDomain: 'ayra-386206.firebaseapp.com',
    storageBucket: 'ayra-386206.appspot.com',
    measurementId: 'G-SGXL3NGG1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6utBWog_lsq8xXLtMXD6n64tXH-lb5Og',
    appId: '1:1015927427902:android:14378c80f24cc2c18b926f',
    messagingSenderId: '1015927427902',
    projectId: 'ayra-386206',
    storageBucket: 'ayra-386206.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYsltllngINHR0FbmU9NpoYD1hhTBb2aY',
    appId: '1:1015927427902:ios:dc597af247edead08b926f',
    messagingSenderId: '1015927427902',
    projectId: 'ayra-386206',
    storageBucket: 'ayra-386206.appspot.com',
    iosClientId: '1015927427902-cgvk8ri4jqqvh544uinv2b1blijt64ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.ratingAndComment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYsltllngINHR0FbmU9NpoYD1hhTBb2aY',
    appId: '1:1015927427902:ios:dc597af247edead08b926f',
    messagingSenderId: '1015927427902',
    projectId: 'ayra-386206',
    storageBucket: 'ayra-386206.appspot.com',
    iosClientId: '1015927427902-cgvk8ri4jqqvh544uinv2b1blijt64ue.apps.googleusercontent.com',
    iosBundleId: 'com.example.ratingAndComment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE50H8MXYZ3hPbnkgbpFP8zsVUjhtP23o',
    appId: '1:1015927427902:web:f9dd6943c251dc0a8b926f',
    messagingSenderId: '1015927427902',
    projectId: 'ayra-386206',
    authDomain: 'ayra-386206.firebaseapp.com',
    storageBucket: 'ayra-386206.appspot.com',
    measurementId: 'G-DCCRYPPBT6',
  );
}
